name: Build and deploy .NET application to container app acmeweb-app-20240516134742
on:
  push:
    branches:
    - main
env:
  CONTAINER_APP_CONTAINER_NAME: acmeweb
  CONTAINER_APP_NAME: acmeweb-app-20240516134742
  CONTAINER_APP_RESOURCE_GROUP_NAME: az204-rg
  CONTAINER_REGISTRY_LOGIN_SERVER: acmeweb20240516134909.azurecr.io
  DOCKER_FILE_PATH: AcmeWeb/Dockerfile
  PROJECT_NAME_FOR_DOCKER: acmeweb
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AcmeWeb20240516134909_USERNAME_1059 }}
        password: ${{ secrets.AcmeWeb20240516134909_PASSWORD_1059 }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.acmeweb_app_20240516134742_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.AcmeWeb20240516134909_USERNAME_1059 }} --password ${{ secrets.AcmeWeb20240516134909_PASSWORD_1059 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
